version: '3.8'

#для подключения к БД в поле HOST .env файла должно быть указано db
services:
  db:
    image: sameersbn/postgresql:10-2
    container_name: postgresql_db
    environment:
      PG_PASSWORD: pacan334
    restart: always
    ports:
      - 5432:5432
    networks:
      - tg_bot
    volumes:
      - ./postgres:/var/lib/postgresql

  server:
    container_name: server
    environment:
      NOTIFY_DSN: "host=db user=postgres password=pacan334 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      NOTIFY_SERVER_PORT: 443
      NOTIFY_API_KEY: "golobar"
      NOTIFY_DOMAIN: "pablogolobar.ru"
    stop_signal: SIGINT
    image: pablogolobar/notify_server:1.0.8
    build:
      context: .
      target: production
      dockerfile: ./docker/server/Dockerfile
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - tg_bot
    depends_on:
      - db
  bot:
    image: pablogolobar/notify_bot:1.0.7
    build:
      context: .
      target: production
      dockerfile: ./docker/tg_bot/Dockerfile
    stop_signal: SIGINT
    restart: always
    networks:
      - tg_bot
    depends_on:
      - db
networks:
  tg_bot:
    driver: bridge
