version: "3.8"

services:
  db:
    image: sameersbn/postgresql:10-2
    container_name: postgresql_db
    environment:
      PG_PASSWORD: pacan334
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql
  server:
    container_name: notifier-dev
    environment:
      NOTIFY_DSN: "host=db user=postgres password=pacan334 dbname=postgres port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      NOTIFY_SERVER_PORT: 8080
      NOTIFY_API_KEY: golobar
    restart: always
    stop_signal: SIGINT
    build:
      context: .
      target: development
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
  bot:
    container_name: tg_bot
    build:
      context: .
      target: development
      dockerfile: ./docker/tg_bot/Dockerfile
    volumes:
      - .:/app
    stop_signal: SIGINT
    restart: always
    networks:
      - tg_bot
    depends_on:
      - db
