basePath: /api/v1
definitions:
  models.Birthday:
    properties:
      birth_date:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      full_name:
        type: string
      id:
        type: integer
      phone_number:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: martin7.heinz@gmail.com
    name: API Support
  description: Swagger API for Golang Project Blueprint.
  license:
    name: MIT
    url: https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Blueprint Swagger API
  version: "1.0"
paths:
  /birthdays/{id}:
    get:
      parameters:
      - description: Birthday ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Birthday'
      security:
      - ApiKeyAuth: []
      summary: Retrieves birthday based on given ID
  /birthdays/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: objects
      security:
      - ApiKeyAuth: []
      summary: Retrieves all birthdays
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
